-- ========================================================
-- GACIA ERP - SUBCATEGORIES SCHEMA 
-- ========================================================

-- 1. Create subcategories table
CREATE TABLE IF NOT EXISTS public.subcategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category_id bigint REFERENCES public.categories(id) ON DELETE CASCADE,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Add subcategory_id to products table
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='subcategory_id') THEN
        ALTER TABLE public.products ADD COLUMN subcategory_id bigint REFERENCES public.subcategories(id) ON DELETE SET NULL;
    END IF;
END $$;

-- 3. Enable RLS
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
DROP POLICY IF EXISTS "Permitir lectura pública de subcategorías" ON public.subcategories;
CREATE POLICY "Permitir lectura pública de subcategorías" ON public.subcategories
FOR SELECT TO anon USING (active = true);

-- Policy for authenticated users (Admins and Staff to manage)
DROP POLICY IF EXISTS "Permitir todo a autenticados en subcategorías" ON public.subcategories;
CREATE POLICY "Permitir todo a autenticados en subcategorías" ON public.subcategories
FOR ALL TO authenticated USING (true);

-- 5. Comments
COMMENT ON TABLE public.subcategories IS 'Subcategorías de productos vinculadas a categorías principales.';
