-- ========================================================
-- GACIA ERP - CASH BOXES (CAJAS) SYSTEM
-- ========================================================

-- 1. Create Cash Boxes table
CREATE TABLE IF NOT EXISTS public.cash_boxes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id bigint REFERENCES public.branches(id) ON DELETE CASCADE,
    name text NOT NULL,
    balance numeric DEFAULT 0,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(branch_id, name)
);

-- 2. Create Cash Movements table (Audit Log)
CREATE TABLE IF NOT EXISTS public.cash_movements (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    cash_box_id bigint REFERENCES public.cash_boxes(id) ON DELETE CASCADE,
    amount numeric NOT NULL,
    type text NOT NULL, -- INGRESO, EGRESO
    description text,
    reference_id text, -- sale_id, purchase_id, etc.
    user_id uuid REFERENCES public.profiles(id),
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Add cash_box_id to transactions
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS cash_box_id bigint REFERENCES public.cash_boxes(id);
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS cash_box_id bigint REFERENCES public.cash_boxes(id);
ALTER TABLE public.customer_payments ADD COLUMN IF NOT EXISTS cash_box_id bigint REFERENCES public.cash_boxes(id);

-- 4. Enable RLS
ALTER TABLE public.cash_boxes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_movements ENABLE ROW LEVEL SECURITY;

-- 5. Basic RLS Policies (Admins can do everything)
CREATE POLICY "Cash boxes allow all for admins" ON public.cash_boxes FOR ALL USING (public.is_admin());
CREATE POLICY "Cash boxes allow read for authenticated" ON public.cash_boxes FOR SELECT USING (true);

CREATE POLICY "Cash movements allow all for admins" ON public.cash_movements FOR ALL USING (public.is_admin());
CREATE POLICY "Cash movements allow read for authenticated" ON public.cash_movements FOR SELECT USING (true);

-- 6. Trigger Logic to update balance and log movement
CREATE OR REPLACE FUNCTION public.fn_process_cash_movement()
RETURNS TRIGGER AS $$
DECLARE
    v_cash_box_id bigint;
    v_amount numeric;
    v_type text;
    v_desc text;
    v_user_id uuid;
    v_branch_id bigint;
BEGIN
    -- Determine table and extract data
    IF TG_TABLE_NAME = 'sales' THEN
        v_cash_box_id := NEW.cash_box_id;
        v_amount := NEW.total;
        v_type := 'INGRESO';
        v_desc := 'Venta #' || NEW.sale_number;
        v_user_id := NEW.user_id;
        v_branch_id := NEW.branch_id;
        
        -- Only process if payment is 'Efectivo' and not a credit
        IF NEW.payment_method != 'Efectivo' OR NEW.is_credit = true THEN
            RETURN NEW;
        END IF;

    ELSIF TG_TABLE_NAME = 'purchases' THEN
        v_cash_box_id := NEW.cash_box_id;
        v_amount := NEW.total;
        v_type := 'EGRESO';
        v_desc := 'Compra #' || NEW.purchase_number;
        v_user_id := NEW.user_id;
        v_branch_id := NEW.branch_id;

    ELSIF TG_TABLE_NAME = 'customer_payments' THEN
        v_cash_box_id := NEW.cash_box_id;
        v_amount := NEW.amount;
        v_type := 'INGRESO';
        v_desc := 'Pago de Cliente';
        v_user_id := NEW.user_id; -- Might be null if not tracked, but profiles has it
        
        IF NEW.payment_method != 'Efectivo' THEN
            RETURN NEW;
        END IF;
    END IF;

    -- Basic validation
    IF v_cash_box_id IS NULL THEN
        RETURN NEW;
    END IF;

    -- Update Box Balance
    IF v_type = 'INGRESO' THEN
        UPDATE public.cash_boxes SET balance = balance + v_amount WHERE id = v_cash_box_id;
    ELSE
        UPDATE public.cash_boxes SET balance = balance - v_amount WHERE id = v_cash_box_id;
    END IF;

    -- Log Movement
    INSERT INTO public.cash_movements (cash_box_id, amount, type, description, reference_id, user_id)
    VALUES (v_cash_box_id, v_amount, v_type, v_desc, NEW.id::text, v_user_id);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Apply Triggers
DROP TRIGGER IF EXISTS trg_sales_cash_movement ON public.sales;
CREATE TRIGGER trg_sales_cash_movement AFTER INSERT ON public.sales FOR EACH ROW EXECUTE FUNCTION public.fn_process_cash_movement();

DROP TRIGGER IF EXISTS trg_purchases_cash_movement ON public.purchases;
CREATE TRIGGER trg_purchases_cash_movement AFTER INSERT ON public.purchases FOR EACH ROW EXECUTE FUNCTION public.fn_process_cash_movement();

DROP TRIGGER IF EXISTS trg_payments_cash_movement ON public.customer_payments;
CREATE TRIGGER trg_payments_cash_movement AFTER INSERT ON public.customer_payments FOR EACH ROW EXECUTE FUNCTION public.fn_process_cash_movement();

-- 8. Add a default box for each branch if none exists
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT id, name FROM public.branches WHERE active = true LOOP
        INSERT INTO public.cash_boxes (branch_id, name, balance)
        VALUES (r.id, 'Caja Principal ' || r.name, 0)
        ON CONFLICT DO NOTHING;
    END LOOP;
END $$;
